"""empty message

Revision ID: 3f65bb5a8e27
Revises: 
Create Date: 2024-10-17 13:31:34.389716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f65bb5a8e27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fingerprint', schema=None) as batch_op:
        batch_op.drop_column('matricule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fingerprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.VARCHAR(length=8), nullable=True))

    # ### end Alembic commands ###
